dependencies:
  comment: |
    This is an automated pull request by @dependabot, a service we use to keep libraries up to date in our projects. Read this post to learn how to help us understand if it's ready to be merged (there are lots of considerations to balance!): https://bit.ly/3GphOhV
