require: rubocop-rails
require: rubocop-performance

# Start with Spotifys style guide as a base then customize from there
inherit_from:
  - .rubocop_todo.yml

inherit_gem:
  rubocop-shopify: rubocop.yml

# Apply rule to all cops
AllCops:
  Include:
    - '*/**/*.rb'
    - '/Rakefile'
    - '/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'spec/**/*'
    - 'bin/*'
    - 'doc/*'
    - 'log/*'
    - 'db/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'script/**/*'
    - 'lib/**/*'
    - 'test/**/*'
    - 'public/**/*'
    - 'Dangerfile'
    - 'app/views/**/*'
    - 'app/assets/javascripts/application.js'
  TargetRubyVersion: '2.4'

Layout/MultilineMethodCallIndentation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/DefEndAlignment:
  Enabled: false

Lint/SafeNavigationChain:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/LineLength:
  Max: 423

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/WordArray:
  Enabled: true
  EnforcedStyle: percent

Performance/AncestorsInclude: # new in 1.7
  Enabled: true

Performance/BigDecimalWithNumericArgument: # new in 1.7
  Enabled: true

Performance/BlockGivenWithExplicitBlock: # new in 1.9
  Enabled: true

Performance/CollectionLiteralInLoop: # new in 1.8
  Enabled: true

Performance/ConcurrentMonotonicTime: # new in 1.12
  Enabled: true

Performance/ConstantRegexp: # new in 1.9
  Enabled: true

Performance/MapCompact: # new in 1.11
  Enabled: true

Performance/MethodObjectAsBlock: # new in 1.9
  Enabled: true

Performance/RedundantEqualityComparisonBlock: # new in 1.10
  Enabled: true

Performance/RedundantSortBlock: # new in 1.7
  Enabled: true

Performance/RedundantSplitRegexpArgument: # new in 1.10
  Enabled: true

Performance/RedundantStringChars: # new in 1.7
  Enabled: true

Performance/ReverseFirst: # new in 1.7
  Enabled: true

Performance/SortReverse: # new in 1.7
  Enabled: true

Performance/Squeeze: # new in 1.7
  Enabled: true

Performance/StringIdentifierArgument: # new in 1.13
  Enabled: true

Performance/StringInclude: # new in 1.7
  Enabled: true

Performance/Sum: # new in 1.8
  Enabled: true
