development:
  bucket: "grassrootsmapping"
  access_key_id: 
  secret_access_key: 
test:
  access_key_id: 
  secret_access_key:
production:
  bucket: "grassrootsmapping"
  access_key_id: <%= ENV['AWS_ACCESS_KEY'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
