name: 'Label Actions'
# This workflow is triggered when a label is added to an issue.

on:
  pull_request:
    types: labeled
jobs:
  processLabelAction:
    name: Process Label Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Process Label Action
        uses: hramos/label-actions@v1
        with:
          configuration-path: '.github/label-actions.yml'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
